name: Health Check

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

env:
  HEALTH_ENDPOINT: "/health"
  DOMAIN: ${{ vars.DOMAIN }}

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to /health
        run: |
          if [ -z "$DOMAIN" ]; then
            echo "Domain is not set. Please provide a domain when running the workflow manually."
            exit 1
          fi
          curl -sSf "${DOMAIN}${HEALTH_ENDPOINT}" || echo "Health check failed"
